--- # Create S3 Bucket
-   hosts: localhost
    tasks:
    - name: Create S3 Bucket
      s3_bucket:
        name: jenkins-tfstate-bucket
        state: present
        versioning: yes
        encryption: "AES256"