---
- hosts: localhost
  vars:
    state: "present"
    region: "us-east-1"
    key: "terraform.tfstate"
    bucket: "jenkins-yaml-tfstate-bucket"
    dynamodb_table: "jenkins-yaml-table"
    app_env: "default"

  tasks:
    - name: Run The Terraform Scripts
      terraform:
        project_path: "./"
        state: "{{ state }}"
        force_init: true
        terraform_init: yes
        # backend_config:
        #   region: "{{ region }}"
        #   bucket: "{{ bucket }}"
        #   key: "{{ key }}"
        #   dynamodb_table: "{{ dynamodb_table }}"
        variables_file: "{{ app_env }}.tfvars"
        workspace: "{{ app_env }}"



